# Generated by Django 3.2 on 2025-01-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20250130_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='achievements',
            field=models.ManyToManyField(null=True, through='cats.AchievementCat', to='cats.Achievement'),
        ),
    ]
